# Generated by Django 5.2.12 on 2026-05-15 16:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('sector', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True, max_length=300)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('logo_url', models.URLField(blank=True, max_length=500)),
                ('professional_email', models.EmailField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(db_column='user_id', limit_choices_to={'role': 'admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil entreprise',
                'verbose_name_plural': 'Profils entreprises',
                'db_table': 'company_profiles',
            },
        ),
    ]
