# Generated by Django 5.2.12 on 2026-05-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='internal_note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('reviewed', 'Vue'), ('interview', 'Entretien'), ('accepted', 'Acceptée'), ('rejected', 'Refusée'), ('withdrawn', 'Retirée')], default='pending', max_length=20),
        ),
    ]
