# Generated by Django 5.2.12 on 2026-05-15 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_joboffer_salary'),
        ('matching', '0002_application_internal_note_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='job',
            field=models.ForeignKey(blank=True, db_column='job_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='jobs.joboffer'),
        ),
    ]
