# Generated by Django 5.2.12 on 2026-05-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_savedjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='salary',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
